# Generated by Django 6.0.7 on 2026-07-22 09:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "conversation_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("query_text", models.TextField()),
                ("intent", models.CharField(blank=True, default="", max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("resolved", "Resolved"),
                            ("escalated", "Escalated"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("final_response", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InventoryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=255, unique=True)),
                ("quantity_available", models.IntegerField(default=0)),
                ("restock_eta", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=255)),
                ("item_name", models.CharField(max_length=255)),
                (
                    "item_category",
                    models.CharField(default="electronics", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("placed", "Placed"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("refund_requested", "Refund Requested"),
                        ],
                        default="placed",
                        max_length=20,
                    ),
                ),
                ("order_date", models.DateField()),
                (
                    "tracking_number",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
            options={
                "ordering": ["-order_date"],
            },
        ),
        migrations.CreateModel(
            name="RefundPolicy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_category", models.CharField(max_length=100, unique=True)),
                ("refund_window_days", models.IntegerField(default=30)),
                ("requires_manager_approval", models.BooleanField(default=False)),
            ],
        ),
    ]
