# Generated by Django 6.0.7 on 2026-07-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversationlog",
            name="agents_involved",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="conversationlog",
            name="confidence_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversationlog",
            name="last_agent_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="conversationlog",
            name="was_escalated",
            field=models.BooleanField(default=False),
        ),
    ]
